### ISSUE TITLE
Duplicate Migration on Install.

### ISSUE THREAD

**Issue by Eggotron** [mage2/laravel-ecommerce#69]
The following error appears when using php artisan migrate:

`In Connection.php line 664:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists (SQL: create table
  `oauth_auth_codes` (`id` varchar(100) not null, `user_id` int not null, `client_id` int not null, `scopes` text null
  , `revoked` tinyint(1) not null, `expires_at` datetime null) default character set utf8 collate utf8_unicode_ci engi
  ne = InnoDB)

In Connection.php line 458:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists
`

The only migration file I could find is on the file named: **2017_03_29_000000_mage2_ecommerce_schema.php** on modules/mage2/migrations but couldn't find a duplicate.

Also, is there a reason why the migrations are inside the module? Isn't it better to follow convention and have them on the database/migrations folder?

**Comment by Eggotron** [comment]
Update:
The problem appears at random in different parts of the migration process, not just with table "oauth_auth_codes". 

Is there any way around this issue? The installation is resulting in a tedious process and the documentation isn't clear on this problem. Even when trying to access the page with "php artisan serve" it doesn't open the installation process where it automated the migrations (I think the last time I used this code was 6 months ago but I'm trying to use this new version).

**Comment by indpurvesh** [comment]
@Eggotron  Yes i do agree with your migration file location point. 
In future i will make modules/mage2/ecommerce as an Package so it will be moved to vendor folder.

I will double check with the migrate bug and commit a fix soon.

**Comment by indpurvesh** [comment]
@Eggotron I hope it should be fixed now.

**Comment by dakshhmehta** [comment]
Sorry, but the problem still persist. The problem mentioned by @Eggotron is resolved but has now new problem as the order_statuses table is written after the orders table which has foreign key to the order_statuses table.

Need to move it up. Sending you change, please accept and test once.

**Comment by dakshhmehta** [comment]
@indpurvesh please check the #71 and once merged, @Eggotron your error should be gone.

**Comment by indpurvesh** [comment]
thanks @dakshhmehta it should be fixed.
